### ISSUE TITLE
/system/bin/bu: not found

### ISSUE THREAD

**Issue by Osndok** [TeamWin/android_device_oneplus_oneplus3#4]
As mentioned in #3 , the ability to create backups seems to be broken (at least for me & he). I thought it would be good to create a separate ticket to capture this (hopefully easier) issue.

When creating backups, files are created containing this line of text:
```
/sbin/sh: /system/bin/bu: not found
```

Introspecting via `adb shell` shows that `/system` is an empty directory, and that `/sbin/bu` exists.

This is for an encrypted phone, if that makes a difference, and v3.3.1 (latest).

**Comment by bigbiff** [comment]
Hello, please let me know if https://build.twrp.me/twrp-3.3.1-1-oneplus3.img works

**Comment by Osndok** [comment]
Thanks for getting back with me so soon @bigbiff ... you really didn't have to! I'm pleased to report that the provided binary **DOES FIX** this issue!

**Comment by bigbiff** [comment]
Thanks, I am releasing an official update now.

**Comment by hacker1024** [comment]
@bigbiff  I'm getting this issue on my Amazon Fire HD 8 (douglas). What was the cause, and how did you fix it?

**Comment by bigbiff** [comment]
It needed rebuilt. I don't see douglas on our jenkins.
